alias themes='/home/douglashall/scripts/themes.sh'
alias edxapp='/home/douglashall/scripts/edxapp.sh'
alias edxapp_restart='/home/douglashall/scripts/edxapp_restart.sh'
alias edxapp_upgrade='/home/douglashall/scripts/edxapp_upgrade.sh'
alias ecommerce='/home/douglashall/scripts/ecommerce.sh'
alias ecommerce_restart='/home/douglashall/scripts/ecommerce_restart.sh'
